export default {
	address: 'address',
	address_status: 'address_status',
	author: 'author',
	book: 'book',
	book_author: 'book_author',
	books_language: 'books_language',
	customer: 'customer',
	customer_address: 'customer_address',
	customer_order: 'customer_order',
	order_line: 'order_line',
	order_history: 'order_history',
	order_status: 'order_status',
	shipping_method: 'shipping_method',
	publisher: 'publisher',
	region: 'region',
}
