// /**
//  * @param { import("knex").Knex } knex
//  * @returns { Promise<void> }
//  */
// export async function seed(knex) {
// 	// Deletes ALL existing entries
// 	await knex('author').del()
// 	await knex('author').insert([
// 		{ author_name: 'A. Bartlett Giamatti' },
// 		{ author_name: 'A. Elizabeth Delany' },
// 		{ author_name: 'A. Merritt' },
// 		{ author_name: 'A. Roger Merrill' },
// 		{ author_name: 'A. Walton Litz' },
// 		{ author_name: 'A.B. Yehoshua' },
// 		{ author_name: 'A.D.P. Briggs' },
// 		{ author_name: 'A.E. Cunningham' },
// 		{ author_name: 'A.E. van Vogt' },
// 		{ author_name: 'A.G. Pasquella' },
// 		{ author_name: 'A.H. Armstrong' },
// 		{ author_name: 'A.J. Arberry' },
// 		{ author_name: 'A.J. Ayer' },
// 		{ author_name: 'A.J. Jacobs' },
// 		{ author_name: 'A.J. McAllister' },
// 		{ author_name: 'A.M. Dellamonica' },
// 		{ author_name: 'A.M. Homes' },
// 		{ author_name: 'A.N. Roquelaure' },
// 		{ author_name: 'A.N. Wilson' },
// 		{ author_name: 'A.R. Braunmuller' },
// 		{ author_name: 'A.R. Taylor' },
// 		{ author_name: 'A.S. Byatt' },
// 		{ author_name: 'A.T. Hatto' },
// 		{ author_name: 'A.V. Miller' },
// 		{ author_name: 'Aaron Anderson' },
// 		{ author_name: 'Aaron Asher' },
// 		{ author_name: 'Aaron Medwin' },
// 		{ author_name: 'Aaron Rosenberg' },
// 		{ author_name: 'Aaron Shepard' },
// 		{ author_name: 'Abbe Wool' },
// 		{ author_name: 'Abbie Hoffman' },
// 		{ author_name: 'Abdul Rahman Munif' },
// 		{ author_name: 'Abdul-Karim Mustapha' },
// 		{ author_name: 'Abigail Adams' },
// 		{ author_name: 'Abigail Thomas' },
// 		{ author_name: 'Abolqasem Ferdowsi' },
// 		{ author_name: 'Abraham Lincoln' },
// 		{ author_name: 'Abraham Moore' },
// 		{ author_name: 'Adam Sexton' },
// 		{ author_name: 'Adam Drozdek' },
// 		{ author_name: 'Adam Gauntlett' },
// 		{ author_name: 'Adam Ginsberg' },
// 		{ author_name: 'Adam Golaski' },
// 		{ author_name: 'Adam Gopnik' },
// 		{ author_name: 'Adam Hargreaves' },
// 		{ author_name: 'Adam Haslett' },
// 		{ author_name: 'Adam Hochschild' },
// 		{ author_name: 'Adam Lesh' },
// 		{ author_name: 'Adam Long' },
// 		{ author_name: 'Adam Mansbach' },
// 		{ author_name: 'Adam Mars-Jones' },
// 		{ author_name: 'Adam McCauley' },
// 		{ author_name: 'Adam Phillips' },
// 		{ author_name: 'Adam Rex' },
// 		{ author_name: 'Adam Roberts' },
// 		{ author_name: 'Adam Smith' },
// 		{ author_name: 'Adam Swift' },
// 		{ author_name: 'Adam Woog' },
// 		{ author_name: 'Adam-Troy Castro' },
// 		{ author_name: 'Adela Pinch' },
// 		{ author_name: 'Adèle Geras' },
// 		{ author_name: 'Adèle Lang' },
// 		{ author_name: 'Adi Granov' },
// 		{ author_name: 'Adolfo Bioy Casares' },
// 		{ author_name: 'Adolfo Pérez Perdomo' },
// 		{ author_name: 'Adrian Reynolds' },
// 		{ author_name: 'Adrian Alphona' },
// 		{ author_name: 'Adrian Esteban' },
// 		{ author_name: 'Adrián Ferrero' },
// 		{ author_name: 'Adrian Geoffrey Gilbert' },
// 		{ author_name: 'Adrian Guelke' },
// 		{ author_name: 'Adrian Lester' },
// 		{ author_name: 'Adrian McKinty' },
// 		{ author_name: 'Adrian Wootton' },
// 		{ author_name: 'Adrienne Theimer' },
// 		{ author_name: 'Aeon J. Skoble' },
// 		{ author_name: 'Aeschylus' },
// 		{ author_name: 'Aesop' },
// 		{ author_name: 'Agatha Christie' },
// 		{ author_name: 'Agnes D. Kingston' },
// 		{ author_name: 'Agnolo di Cosimo Bronzino' },
// 		{ author_name: 'Ai Morinaga' },
// 		{ author_name: 'Aidan Hartley' },
// 		{ author_name: 'Aimé Césaire' },
// 		{ author_name: 'Aimee Bender' },
// 		{ author_name: 'Aimee Friedman' },
// 		{ author_name: 'Aine Greaney' },
// 		{ author_name: 'Akhil Sharma' },
// 		{ author_name: 'Akihiro Yamada' },
// 		{ author_name: 'Akira Watanabe' },
// 		{ author_name: 'Akira Yoshida' },
// 		{ author_name: 'Al Dempster' },
// 		{ author_name: 'Al Franken' },
// 		{ author_name: 'Al Gore' },
// 		{ author_name: 'Al Ries' },
// 		{ author_name: 'Al Rio' },
// 		{ author_name: 'Al Switzler' },
// 		{ author_name: 'Alafair Burke' },
// 		{ author_name: 'Alain de Botton' },
// 		{ author_name: 'Alain Defossé' },
// 		{ author_name: 'Alain Korkos' },
// 		{ author_name: 'Alak Zenkar' },
// 		{ author_name: 'Alan Lee' },
// 		{ author_name: 'Alan Aldridge' },
// 		{ author_name: 'Alan Brennert' },
// 		{ author_name: 'Alan Cohen' },
// 		{ author_name: 'Alan Dean Foster' },
// 		{ author_name: 'Alan Durband' },
// 		{ author_name: 'Alan Ereira' },
// 		{ author_name: 'Alan Greenspan' },
// 		{ author_name: 'Alan H. Sommerstein' },
// 		{ author_name: 'Alan Hausman' },
// 		{ author_name: 'Alan Hollinghurst' },
// 		{ author_name: 'Alan Jay Lerner' },
// 		{ author_name: 'Alan Jolis' },
// 		{ author_name: 'Alan Judd' },
// 		{ author_name: 'Alan Langford' },
// 		{ author_name: 'Alan Lightman' },
// 		{ author_name: 'Alan MacGillivray' },
// 		{ author_name: 'Alan Moore' },
// 		{ author_name: 'Alan Myers' },
// 		{ author_name: 'Alan Paton' },
// 		{ author_name: 'Alan R. Clarke' },
// 		{ author_name: 'Alan Rosenus' },
// 		{ author_name: 'Alan Shapiro' },
// 		{ author_name: 'Alan Witschonke' },
// 		{ author_name: 'Alastair Hamilton' },
// 		{ author_name: 'Alastair Hannay' },
// 		{ author_name: 'Alastair Lamb' },
// 		{ author_name: 'Alastair McEwen' },
// 		{ author_name: 'Alastair Reid' },
// 		{ author_name: 'Alastair Westgarth' },
// 		{ author_name: 'Albert Camus' },
// 		{ author_name: 'Albert Demeo' },
// 		{ author_name: 'Albert Einstein' },
// 		{ author_name: 'Albert Ellis' },
// 		{ author_name: 'Albert G. Spalding' },
// 		{ author_name: 'Albert Hackett' },
// 		{ author_name: 'Albert Hofstadter' },
// 		{ author_name: 'Albert Jack' },
// 		{ author_name: 'Albert Lee Strickland' },
// 		{ author_name: 'Albert Marrin' },
// 		{ author_name: 'Albert Speer' },
// 		{ author_name: 'Albert Wittstock' },
// 		{ author_name: 'Alberto Coscarelli' },
// 		{ author_name: 'Alcoholics Anonymous' },
// 		{ author_name: 'Alden T. Vaughan' },
// 		{ author_name: 'Aldon D. Morris' },
// 		{ author_name: 'Aldous Huxley' },
// 		{ author_name: 'Alec Effinger' },
// 		{ author_name: 'Alec MacLellan' },
// 		{ author_name: 'Alec Stevens' },
// 		{ author_name: 'Aleksandar Hemon' },
// 		{ author_name: 'Aleksandr Ivanovich Kuprin' },
// 		{ author_name: 'Aleksandr Solzhenitsyn' },
// 		{ author_name: 'Aleksey Ivanov' },
// 		{ author_name: 'Alev Lytle Croutier' },
// 		{ author_name: 'Alex Austin' },
// 		{ author_name: 'Alex C. Jones' },
// 		{ author_name: 'Alex Constantine' },
// 		{ author_name: 'Alex Cox' },
// 		{ author_name: 'Alex Garland' },
// 		{ author_name: 'Alex Gaskarth' },
// 		{ author_name: 'Alex Kava' },
// 		{ author_name: 'Alex Kershaw' },
// 		{ author_name: 'Alex Kotlowitz' },
// 		{ author_name: 'Alex Prud\'Homme' },
// 		{ author_name: 'Alex Robinson' },
// 		{ author_name: 'Alex Ross' },
// 		{ author_name: 'Alex Went' },
// 		{ author_name: 'Alexander Walker' },
// 		{ author_name: 'Alexander C. Irvine' },
// 		{ author_name: 'Alexander Heidel' },
// 		{ author_name: 'Alexander Hunter' },
// 		{ author_name: 'Alexander McCall Smith' },
// 		{ author_name: 'Alexander Nehamas' },
// 		{ author_name: 'Alexander O. Smith' },
// 		{ author_name: 'Alexander Payne' },
// 		{ author_name: 'Alexander Pope' },
// 		{ author_name: 'Alexander Pushkin' },
// 		{ author_name: 'Alexander Scourby' },
// 		{ author_name: 'Alexander Theroux' },
// 		{ author_name: 'Alexandra Boiger' },
// 		{ author_name: 'Alexandra Ivy' },
// 		{ author_name: 'Alexandra Moss' },
// 		{ author_name: 'Alexandra Robbins' },
// 		{ author_name: 'Alexandra Siy' },
// 		{ author_name: 'Alexandra Wallner' },
// 		{ author_name: 'Alexandre Dumas' },
// 		{ author_name: 'Alexandre Dumas fils' },
// 		{ author_name: 'Alexis de Tocqueville' },
// 		{ author_name: 'Alexis Kirsch' },
// 		{ author_name: 'Alfred Appel' },
// 		{ author_name: 'Alfred Bester' },
// 		{ author_name: 'Alfred Birnbaum' },
// 		{ author_name: 'Alfred D. Chandler Jr.' },
// 		{ author_name: 'Alfred Hitchcock' },
// 		{ author_name: 'Alfred Huang' },
// 		{ author_name: 'Alfred J. Church' },
// 		{ author_name: 'Alfred Siewers' },
// 		{ author_name: 'Alfred Uhry' },
// 		{ author_name: 'Alfredo Crespo' },
// 		{ author_name: 'Algernon Blackwood' },
// 		{ author_name: 'Ali Douglass' },
// 		{ author_name: 'Ali Vali' },
// 		{ author_name: 'Alice Miller' },
// 		{ author_name: 'Alice Dalgliesh' },
// 		{ author_name: 'Alice Hoffman' },
// 		{ author_name: 'Alice Hudson' },
// 		{ author_name: 'Alice Kaplan' },
// 		{ author_name: 'Alice Mayhew' },
// 		{ author_name: 'Alice Medrich' },
// 		{ author_name: 'Alice Munro' },
// 		{ author_name: 'Alice Randall' },
// 		{ author_name: 'Alice Sebold' },
// 		{ author_name: 'Alice Walker' },
// 		{ author_name: 'Alice Wong' },
// 		{ author_name: 'Alicia Suskin Ostriker' },
// 		{ author_name: 'Alisa Freedman' },
// 		{ author_name: 'Alisa Klayman-Grodsky' },
// 		{ author_name: 'Alisa Valdes' },
// 		{ author_name: 'Alison Anderson' },
// 		{ author_name: 'Alison Baverstock' },
// 		{ author_name: 'Alison Bechdel' },
// 		{ author_name: 'Alison Boardman' },
// 		{ author_name: 'Alison Goodman' },
// 		{ author_name: 'Alison Kent' },
// 		{ author_name: 'Alison Leslie Gold' },
// 		{ author_name: 'Alison Lurie' },
// 		{ author_name: 'Alison Pace' },
// 		{ author_name: 'Alison Weir' },
// 		{ author_name: 'Alistair Horne' },
// 		{ author_name: 'Alistair MacLeod' },
// 		{ author_name: 'Alistair McCallum' },
// 		{ author_name: 'Alistair Moffat' },
// 		{ author_name: 'Alistair Welchman' },
// 		{ author_name: 'Alister E. McGrath' },
// 		{ author_name: 'Aljean Harmetz' },
// 		{ author_name: 'Allan Bloom' },
// 		{ author_name: 'Allan C. Weisbecker' },
// 		{ author_name: 'Allan Cameron' },
// 		{ author_name: 'Allan Curless' },
// 		{ author_name: 'Allan Drummond' },
// 		{ author_name: 'Allan Janik' },
// 		{ author_name: 'Allan Kozinn' },
// 		{ author_name: 'Allan Rosenberg' },
// 		{ author_name: 'Allan Ulrich' },
// 		{ author_name: 'Allan Zola Kronzek' },
// 		{ author_name: 'Allegra Goodman' },
// 		{ author_name: 'Allen Carr' },
// 		{ author_name: 'Allen Ginsberg' },
// 		{ author_name: 'Allen J. Frantzen' },
// 		{ author_name: 'Allen Mackey' },
// 		{ author_name: 'Allen Mandelbaum' },
// 		{ author_name: 'Allen Noren' },
// 		{ author_name: 'Allen Rogers Benner' },
// 		{ author_name: 'Allen W. Wood' },
// 		{ author_name: 'Allison Markin Powell' },
// 		{ author_name: 'Allison Pearson' },
// 		{ author_name: 'Alma Flor Ada' },
// 		{ author_name: 'Alma MacDougall Reising' },
// 		{ author_name: 'Alonzo C. Addison' },
// 		{ author_name: 'Alton Raible' },
// 		{ author_name: 'Alvin L. Reid' },
// 		{ author_name: 'Alyssa Harad' },
// 		{ author_name: 'Amanda Ann Klein' },
// 		{ author_name: 'Amanda Clark' },
// 		{ author_name: 'Amanda Eyre Ward' },
// 		{ author_name: 'Amanda Hemingway' },
// 		{ author_name: 'Amanda Hopkinson' },
// 		{ author_name: 'Amanda Root' },
// 		{ author_name: 'Amartya Sen' },
// 		{ author_name: 'Ambrose Bierce' },
// 		{ author_name: 'Amelia Atwater-Rhodes' },
// 		{ author_name: 'America\'s Test Kitchen' },
// 		{ author_name: 'American Academy of Pediatrics' },
// 		{ author_name: 'Amiira Ruotola {-Behrendt}' },
// 		{ author_name: 'Amir D. Aczel' },
// 		{ author_name: 'Amiri Baraka' },
// 		{ author_name: 'Amitav Ghosh' },
// 		{ author_name: 'Amos Oz' },
// 		{ author_name: 'Amy Berner' },
// 		{ author_name: 'Amy Carter' },
// 		{ author_name: 'Amy Cotler' },
// 		{ author_name: 'Amy Goldman Koss' },
// 		{ author_name: 'Amy Gutmann' },
// 		{ author_name: 'Amy H. Sturgis' },
// 		{ author_name: 'Amy Hempel' },
// 		{ author_name: 'Amy Hill Hearth' },
// 		{ author_name: 'Amy Krouse Rosenthal' },
// 		{ author_name: 'Amy L. Marsland' },
// 		{ author_name: 'Amy Mandelker' },
// 		{ author_name: 'Amy Sedaris' },
// 		{ author_name: 'Amy Sickels' },
// 		{ author_name: 'Amy Sohn' },
// 		{ author_name: 'Amy Tan' },
// 		{ author_name: 'Amy Taubin' },
// 		{ author_name: 'Amy Welborn' },
// 		{ author_name: 'Ana Alcaina' },
// 		{ author_name: 'Ana Alcaina Pérez' },
// 		{ author_name: 'Ana Falcão Bastos' },
// 		{ author_name: 'Ana Juan' },
// 		{ author_name: 'Ana María de la Fuente' },
// 		{ author_name: 'Anaïs Nin' },
// 		{ author_name: 'Anaximander' },
// 		{ author_name: 'Anaximenes' },
// 		{ author_name: 'Anca Munteanu' },
// 		{ author_name: 'Ande Parks' },
// 		{ author_name: 'Anders Nilsen' },
// 		{ author_name: 'Anderson Cooper' },
// 		{ author_name: 'Andre Dubus' },
// 		{ author_name: 'Andre Dubus III' },
// 		{ author_name: 'Andre Duza' },
// 		{ author_name: 'André Maurois' },
// 		{ author_name: 'Andre Norton' },
// 		{ author_name: 'Andrea Camilleri' },
// 		{ author_name: 'Andrea Juno' },
// 		{ author_name: 'Andrea Levy' },
// 		{ author_name: 'Andrea Lingenfelter' },
// 		{ author_name: 'Andrea Wilson Nightingale' },
// 		{ author_name: 'Andreas Schwarz' },
// 		{ author_name: 'Andreas Gursky' },
// 		{ author_name: 'Andreas J. Köstenberger' },
// 		{ author_name: 'Andrei Codrescu' },
// 		{ author_name: 'Andrés Duany' },
// 		{ author_name: 'Andrew Hunt' },
// 		{ author_name: 'Andrew Hunt' },
// 		{ author_name: 'Andrew Brown' },
// 		{ author_name: 'Andrew Carnegie' },
// 		{ author_name: 'Andrew Cartmel' },
// 		{ author_name: 'Andrew Collins' },
// 		{ author_name: 'Andrew Darling' },
// 		{ author_name: 'Andrew Delbanco' },
// 		{ author_name: 'Andrew Dennis' },
// 		{ author_name: 'Andrew Edwin Jenkins' },
// 		{ author_name: 'Andrew Elfenbein' },
// 		{ author_name: 'Andrew Ford' },
// 		{ author_name: 'Andrew Glass' },
// 		{ author_name: 'Andrew Gross' },
// 		{ author_name: 'Andrew Gurr' },
// 		{ author_name: 'Andrew Heintzman' },
// 		{ author_name: 'Andrew Helfer' },
// 		{ author_name: 'Andrew Hurley' },
// 		{ author_name: 'Andrew Hussey' },
// 		{ author_name: 'Andrew J. Offutt' },
// 		{ author_name: 'Andrew James McLean' },
// 		{ author_name: 'Andrew Klavan' },
// 		{ author_name: 'Andrew Lang' },
// 		{ author_name: 'Andrew Leak' },
// 		{ author_name: 'Andrew M. Greeley' },
// 		{ author_name: 'Andrew McNeillie' },
// 		{ author_name: 'Andrew Moore' },
// 		{ author_name: 'Andrew O\'Hagan' },
// 		{ author_name: 'Andrew P. Trout' },
// 		{ author_name: 'Andrew Pepoy' },
// 		{ author_name: 'Andrew R. MacAndrew' },
// 		{ author_name: 'Andrew Robert Burn' },
// 		{ author_name: 'Andrew S. Becker' },
// 		{ author_name: 'Andrew Scull' },
// 		{ author_name: 'Andrew Solomon' },
// 		{ author_name: 'Andrew Weil' },
// 		{ author_name: 'Andrew X. Pham' },
// 		{ author_name: 'Andy Crouch' },
// 		{ author_name: 'Andy Frankham-Allen' },
// 		{ author_name: 'Andy Gordon' },
// 		{ author_name: 'Andy Griffiths' },
// 		{ author_name: 'Andy Grundberg' },
// 		{ author_name: 'Andy Hertzfeld' },
// 		{ author_name: 'Andy Hunt' },
// 		{ author_name: 'Andy Kubert' },
// 		{ author_name: 'Andy Mastrocinque' },
// 		{ author_name: 'Andy McNab' },
// 		{ author_name: 'Andy Russell' },
// 		{ author_name: 'Andy Warhol' },
// 		{ author_name: 'Anette M. Pedersen' },
// 		{ author_name: 'Angel M.Y. Lin' },
// 		{ author_name: 'Angela Barrett' },
// 		{ author_name: 'Angela Carter' },
// 		{ author_name: 'Angela J. Linn' },
// 		{ author_name: 'Angela Knight' },
// 		{ author_name: 'Angela Scholar' },
// 		{ author_name: 'Angela Zeman' },
// 		{ author_name: 'Angelo Rinaldi' },
// 		{ author_name: 'Angus Easson' },
// 		{ author_name: 'Angus Gellatly' },
// 		{ author_name: 'Angus Wells' },
// 		{ author_name: 'Anita Desai' },
// 		{ author_name: 'Anita Diamant' },
// 		{ author_name: 'Anita Hoffman' },
// 		{ author_name: 'Anita Shreve' },
// 		{ author_name: 'Anita Thompson' },
// 		{ author_name: 'Anjali Singh' },
// 		{ author_name: 'Anjelica Huston' },
// 		{ author_name: 'Ann Douglas' },
// 		{ author_name: 'Ann O\'Leary' },
// 		{ author_name: 'Ann Abramson' },
// 		{ author_name: 'Ann Bausum' },
// 		{ author_name: 'Ann Beattie' },
// 		{ author_name: 'Ann Brashares' },
// 		{ author_name: 'Ann Charters' },
// 		{ author_name: 'Ann Druyan' },
// 		{ author_name: 'Ann Dunnigan' },
// 		{ author_name: 'Ann Finding' },
// 		{ author_name: 'Ann Granger' },
// 		{ author_name: 'Ann Hewetson' },
// 		{ author_name: 'Ann Hodgman' },
// 		{ author_name: 'Ann M. Martin' },
// 		{ author_name: 'Ann Major' },
// 		{ author_name: 'Ann Margaret Lewis' },
// 		{ author_name: 'Ann Maxwell' },
// 		{ author_name: 'Ann McGovern' },
// 		{ author_name: 'Ann Packer' },
// 		{ author_name: 'Ann Page' },
// 		{ author_name: 'Ann Patchett' },
// 		{ author_name: 'Ann Rinaldi' },
// 		{ author_name: 'Ann Romines' },
// 		{ author_name: 'Ann Rule' },
// 		{ author_name: 'Ann Schweninger' },
// 		{ author_name: 'Ann Tashi Slater' },
// 		{ author_name: 'Ann Thompson' },
// 		{ author_name: 'Ann Thwaite' },
// 		{ author_name: 'Ann-Marie MacDonald' },
// 		{ author_name: 'Anna Austen Lefroy' },
// 		{ author_name: 'Anna Brailovsky' },
// 		{ author_name: 'Anna Deavere Smith' },
// 		{ author_name: 'Anna Fields' },
// 		{ author_name: 'Anna Hamilton Phelan' },
// 		{ author_name: 'Anna J.' },
// 		{ author_name: 'Anna J. Evans' },
// 		{ author_name: 'Anna Massey' },
// 		{ author_name: 'Anna Maxted' },
// 		{ author_name: 'Anna Moschovakis' },
// 		{ author_name: 'Anna Okabe' },
// 		{ author_name: 'Anna Paterson' },
// 		{ author_name: 'Anna Quindlen' },
// 		{ author_name: 'Anna Sewell' },
// 		{ author_name: 'Anna Tambour' },
// 		{ author_name: 'Anna Wintour' },
// 		{ author_name: 'Annalee Allen' },
// 		{ author_name: 'Annalyn Swan' },
// 		{ author_name: 'Anne Born' },
// 		{ author_name: 'Anne Borchardt' },
// 		{ author_name: 'Anne Brontë' },
// 		{ author_name: 'Anne Carson' },
// 		{ author_name: 'Anne Chisholm' },
// 		{ author_name: 'Anne Dehne' },
// 		{ author_name: 'Anne Easter Smith' },
// 		{ author_name: 'Anne Elizabeth Moore' },
// 		{ author_name: 'Anne Fadiman' },
// 		{ author_name: 'Anne Frank' },
// 		{ author_name: 'Anne Hoppus' },
// 		{ author_name: 'Anne K. Mellor' },
// 		{ author_name: 'Anne Lamott' },
// 		{ author_name: 'Anne Macdonald' },
// 		{ author_name: 'Anne Mazer' },
// 		{ author_name: 'Anne McCaffrey' },
// 		{ author_name: 'Anne McLean' },
// 		{ author_name: 'Anne Michaels' },
// 		{ author_name: 'Anne Millard' },
// 		{ author_name: 'Anne Moody' },
// 		{ author_name: 'Anne Morrow Lindbergh' },
// 		{ author_name: 'Anne Olivier Bell' },
// 		{ author_name: 'Anne Perry' },
// 		{ author_name: 'Anne Rampling' },
// 		{ author_name: 'Anne Rice' },
// 		{ author_name: 'Anne Stuart' },
// 		{ author_name: 'Anne Tyler' },
// 		{ author_name: 'Anne Yvonne Gilbert' },
// 		{ author_name: 'Anne-Marie Duff' },
// 		{ author_name: 'Anne-Marie Martin' },
// 		{ author_name: 'Annette Lavers' },
// 		{ author_name: 'Annette Meyers' },
// 		{ author_name: 'Annette Smith' },
// 		{ author_name: 'Annie Dillard' },
// 		{ author_name: 'Annie Proulx' },
// 		{ author_name: 'Annie Sparrow' },
// 		{ author_name: 'Anonymous' },
// 		{ author_name: 'Anri Itō' },
// 		{ author_name: 'Ansel Adams' },
// 		{ author_name: 'Anselm of Canterbury' },
// 		{ author_name: 'Anthea Bell' },
// 		{ author_name: 'Anthony Lewis' },
// 		{ author_name: 'Anthony Bonner' },
// 		{ author_name: 'Anthony Boucher' },
// 		{ author_name: 'Anthony Bourdain' },
// 		{ author_name: 'Anthony Bower' },
// 		{ author_name: 'Anthony Briggs' },
// 		{ author_name: 'Anthony Burgess' },
// 		{ author_name: 'Anthony Calderbank' },
// 		{ author_name: 'Anthony Cronin' },
// 		{ author_name: 'Anthony Curtis' },
// 		{ author_name: 'Anthony D. Pellegrini' },
// 		{ author_name: 'Anthony DeCurtis' },
// 		{ author_name: 'Anthony E. Wolf' },
// 		{ author_name: 'Anthony F.C. Wallace' },
// 		{ author_name: 'Anthony Gerard' },
// 		{ author_name: 'Anthony Grafton' },
// 		{ author_name: 'Anthony H. Chambers' },
// 		{ author_name: 'Anthony Heald' },
// 		{ author_name: 'Anthony Hern' },
// 		{ author_name: 'Anthony J. Cascardi' },
// 		{ author_name: 'Anthony Kenny' },
// 		{ author_name: 'Anthony Kerringan' },
// 		{ author_name: 'Anthony Kiedis' },
// 		{ author_name: 'Anthony Loyd' },
// 		{ author_name: 'Anthony M. Esolen' },
// 		{ author_name: 'Anthony Mcreavy' },
// 		{ author_name: 'Anthony Minghella' },
// 		{ author_name: 'Anthony Oldcorn' },
// 		{ author_name: 'Anthony Powell' },
// 		{ author_name: 'Anthony Quinton' },
// 		{ author_name: 'Anthony Richard Birley' },
// 		{ author_name: 'Anthony Rizcallah Ferris' },
// 		{ author_name: 'Anthony Robbins' },
// 		{ author_name: 'Anthony S. Fauci' },
// 		{ author_name: 'Anthony Shadid' },
// 		{ author_name: 'Anthony Thorlby' },
// 		{ author_name: 'Anthony Thwaite' },
// 		{ author_name: 'Anthony Tully' },
// 		{ author_name: 'Antoine de Saint-Exupéry' },
// 		{ author_name: 'Anton C. Pegis' },
// 		{ author_name: 'Anton Chekhov' },
// 		{ author_name: 'Anton Lesser' },
// 		{ author_name: 'Anton Myrer' },
// 		{ author_name: 'Antonia Fraser' },
// 		{ author_name: 'Antonia Juhasz' },
// 		{ author_name: 'Antonin Artaud' },
// 		{ author_name: 'Antonina W. Bouis' },
// 		{ author_name: 'Antonio Gramsci' },
// 		{ author_name: 'Antonio Negri' },
// 		{ author_name: 'Antonio Polito' },
// 		{ author_name: 'Antonio Samons' },
// 		{ author_name: 'Antony Beevor' },
// 		{ author_name: 'Antony Johnston' },
// 		{ author_name: 'Antony Shugaar' },
// 		{ author_name: 'Anya Seton' },
// 		{ author_name: 'Apollodorus' },
// 		{ author_name: 'Apostolos N. Athanassakis' },
// 		{ author_name: 'April Jones Prince' },
// 		{ author_name: 'Architecture For Humanity' },
// 		{ author_name: 'Ariel Levy' },
// 		{ author_name: 'Arielle Ford' },
// 		{ author_name: 'Arien Mack' },
// 		{ author_name: 'Aristophanes' },
// 		{ author_name: 'Aristotle' },
// 		{ author_name: 'Arkangel Cast' },
// 		{ author_name: 'Arlene Eisenberg' },
// 		{ author_name: 'Arliss Howard' },
// 		{ author_name: 'Armand Marie Leroi' },
// 		{ author_name: 'Armistead Maupin' },
// 		{ author_name: 'Arnold Gingrich' },
// 		{ author_name: 'Arnold Goldman' },
// 		{ author_name: 'Arnold Kotler' },
// 		{ author_name: 'Arnold Rampersad' },
// 		{ author_name: 'Arnold Vedlitz' },
// 		{ author_name: 'Arnon Grunberg' },
// 		{ author_name: 'Aron Eisenberg' },
// 		{ author_name: 'Art Cooper' },
// 		{ author_name: 'Art Spiegelman' },
// 		{ author_name: 'Art Spielman' },
// 		{ author_name: 'Art Thibert' },
// 		{ author_name: 'Artem Drabkin' },
// 		{ author_name: 'Artemis Cooper' },
// 		{ author_name: 'Arthur Miller' },
// 		{ author_name: 'Arthur Agatston' },
// 		{ author_name: 'Arthur Bennett' },
// 		{ author_name: 'Arthur C. Clarke' },
// 		{ author_name: 'Arthur Conan Doyle' },
// 		{ author_name: 'Arthur Cooper' },
// 		{ author_name: 'Arthur Doye' },
// 		{ author_name: 'Arthur Edward Waite' },
// 		{ author_name: 'Arthur G. Chater' },
// 		{ author_name: 'Arthur Golden' },
// 		{ author_name: 'Arthur Goldhammer' },
// 		{ author_name: 'Arthur H. Samuelson' },
// 		{ author_name: 'Arthur Herzog III' },
// 		{ author_name: 'Arthur J. Roth' },
// 		{ author_name: 'Arthur Knodel' },
// 		{ author_name: 'Arthur Koestler' },
// 		{ author_name: 'Arthur M. Schlesinger Jr.' },
// 		{ author_name: 'Arthur Machen' },
// 		{ author_name: 'Arthur Morey' },
// 		{ author_name: 'Arthur Naiman' },
// 		{ author_name: 'Arthur Nersesian' },
// 		{ author_name: 'Arthur P. Yin' },
// 		{ author_name: 'Arthur Plotnik' },
// 		{ author_name: 'Arthur Pober' },
// 		{ author_name: 'Arthur Rackham' },
// 		{ author_name: 'Arthur Raleigh Humphreys' },
// 		{ author_name: 'Arthur S. Wensinger' },
// 		{ author_name: 'Arthur Schopenhauer' },
// 		{ author_name: 'Arthur Yorinks' },
// 		{ author_name: 'Artists and Writers Guild' },
// 		{ author_name: 'Arto Häilä' },
// 		{ author_name: 'Arturo Pérez-Reverte' },
// 		{ author_name: 'Arundhati Roy' },
// 		{ author_name: 'Ashley Gardner' },
// 		{ author_name: 'Ashley Shannon' },
// 		{ author_name: 'Ashley Wood' },
// 		{ author_name: 'Åsne Seierstad' },
// 		{ author_name: 'Astre Mithrandir' },
// 		{ author_name: 'Astrid Lindgren' },
// 		{ author_name: 'Atul Gawande' },
// 		{ author_name: 'Aubrey de Sélincourt' },
// 		{ author_name: 'Aubrey Williams' },
// 		{ author_name: 'Audre Lorde' },
// 		{ author_name: 'Audrey Niffenegger' },
// 		{ author_name: 'Audrey Penn' },
// 		{ author_name: 'August Derleth' },
// 		{ author_name: 'August Wilson' },
// 		{ author_name: 'Augusten Burroughs' },
// 		{ author_name: 'Augustine of Hippo' },
// 		{ author_name: 'Aurelio Voltaire' },
// 		{ author_name: 'Aurora Echevarría' },
// 		{ author_name: 'Austin Tichenor' },
// 		{ author_name: 'Avatar Polymorph' },
// 		{ author_name: 'Avi' },
// 		{ author_name: 'Avigdor Kahalani' },
// 		{ author_name: 'Avrahm Yarmolinsky' },
// 		{ author_name: 'Ayako Watanabe' },
// 		{ author_name: 'Aylmer Maude' },
// 		{ author_name: 'Ayn Rand' },
// 		{ author_name: 'Azar Nafisi' },
// 		{ author_name: 'Azzedine Haddour' },
// 		{ author_name: 'B. Deutsch' },
// 		{ author_name: 'B. Litt' },
// 		{ author_name: 'B.B. Rogers' },
// 		{ author_name: 'B.C.J.G. Knight' },
// 		{ author_name: 'B.J. McCall' },
// 		{ author_name: 'B.K. Beckwith' },
// 		{ author_name: 'Babette Rothschild' },
// 		{ author_name: 'Babette Smith' },
// 		{ author_name: 'Bagram Ibatoulline' },
// 		{ author_name: 'Baillie Tolkien' },
// 		{ author_name: 'Bambi Eloriaga' },
// 		{ author_name: 'Barack Obama' },
// 		{ author_name: 'Barb Jernigan' },
// 		{ author_name: 'Barbara Newman' },
// 		{ author_name: 'Barbara A. Mowat' },
// 		{ author_name: 'Barbara A. Turner' },
// 		{ author_name: 'Barbara Ann Brennan' },
// 		{ author_name: 'Barbara Berst Adams' },
// 		{ author_name: 'Barbara Bottner' },
// 		{ author_name: 'Barbara Bray' },
// 		{ author_name: 'Barbara Bretton' },
// 		{ author_name: 'Barbara Caruso' },
// 		{ author_name: 'Barbara Cleverly' },
// 		{ author_name: 'Barbara Cohen' },
// 		{ author_name: 'Barbara Coloroso' },
// 		{ author_name: 'Barbara Conklin' },
// 		{ author_name: 'Barbara Cooney' },
// 		{ author_name: 'Barbara Davilman' },
// 		{ author_name: 'Barbara Delaplace' },
// 		{ author_name: 'Barbara E. Martin' },
// 		{ author_name: 'Barbara Ehrenreich' },
// 		{ author_name: 'Barbara Fairchild' },
// 		{ author_name: 'Barbara Hambly' },
// 		{ author_name: 'Barbara Haworth-Attard' },
// 		{ author_name: 'Barbara Kerley' },
// 		{ author_name: 'Barbara Kingsolver' },
// 		{ author_name: 'Barbara Leonie Picard' },
// 		{ author_name: 'Barbara M. Walker' },
// 		{ author_name: 'Barbara Nadel' },
// 		{ author_name: 'Barbara Park' },
// 		{ author_name: 'Barbara Reynolds' },
// 		{ author_name: 'Barbara Richard' },
// 		{ author_name: 'Barbara Siegel' },
// 		{ author_name: 'Barbara Smuts' },
// 		{ author_name: 'Barbara T. Cooper' },
// 		{ author_name: 'Barbara Taylor Bradford' },
// 		{ author_name: 'Barbara W. Tuchman' },
// 		{ author_name: 'Barbara Weiden Boyd' },
// 		{ author_name: 'Barbara Wright' },
// 		{ author_name: 'Bard E. O\'Neill' },
// 		{ author_name: 'Bard Thompson' },
// 		{ author_name: 'Barney Tobey' },
// 		{ author_name: 'Barrett Whitener' },
// 		{ author_name: 'Barrie D. Coate' },
// 		{ author_name: 'Barrie Trinkle' },
// 		{ author_name: 'Barrington Moore Jr.' },
// 		{ author_name: 'Barron\'\'s' },
// 		{ author_name: 'Barry Lopez' },
// 		{ author_name: 'Barry Smith' },
// 		{ author_name: 'Barry Chubin' },
// 		{ author_name: 'Barry Day' },
// 		{ author_name: 'Barry Eisler' },
// 		{ author_name: 'Barry Glassner' },
// 		{ author_name: 'Barry Hughart' },
// 		{ author_name: 'Barry M. Andrews' },
// 		{ author_name: 'Barry Menikoff' },
// 		{ author_name: 'Barry Miles' },
// 		{ author_name: 'Barry Moser' },
// 		{ author_name: 'Barry N. Malzberg' },
// 		{ author_name: 'Barry Pateman' },
// 		{ author_name: 'Barry R. Cournoyer' },
// 		{ author_name: 'Barry Schwartz' },
// 		{ author_name: 'Barry Z. Posner' },
// 		{ author_name: 'Bart D. Ehrman' },
// 		{ author_name: 'Bart G. Farkas' },
// 	])

// 	// await knex('book').del()
// 	// await knex('book').insert([
// 	// {
// 	// 	title: 'The World\'s First Love: Mary  Mother of God',
// 	// 	isbn13: '8987059752',
// 	// 	num_pages: 276,
// 	// 	publication_date: '1996-09-01',
// 	// 	//language_Id: 2,
// 	// 	//publisher_Id: 10,
// 	// },
// 	// {
// 	// 	title: 'The Illuminati',
// 	// 	isbn13: '20049130001',
// 	// 	num_pages: 352,
// 	// 	publication_date: '2004-10-04',
// 	// 	//language_Id: 2,
// 	// 	//publisher_Id: 7,
// 	// },
// 	// {
// 	// 	title: 'The Servant Leader',
// 	// 	isbn13: '23755004321',
// 	// 	num_pages: 128,
// 	// 	publication_date: '2003-03-11',
// 	// 	//language_Id: 2,
// 	// 	//publisher_Id: 7,
// 	// },
// 	// {
// 	// 	title: 'What Life Was Like in the Jewel in the Crown: British India  AD 1600-1905',
// 	// 	isbn13: '34406054602',
// 	// 	num_pages: 168,
// 	// 	publication_date: '1999-09-01',
// 	// 	//language_Id: 3,
// 	// 	//publisher_Id: 8,
// 	// },
// 	// {
// 	// 	title: 'Cliffs Notes on Aristophanes\'Lysistrata  The Birds  The Clouds  The Frogs',
// 	// 	isbn13: '49086007763',
// 	// 	num_pages: 80,
// 	// 	publication_date: '1983-12-29',
// 	// 	//language_Id: 19,
// 	// 	//publisher_Id: 20,
// 	// },
// 	// {
// 	// 	title: 'Life Is a Dream and Other Spanish Classics (Eric Bentley\'s Dramatic Repertoire} - Volume II',
// 	// 	isbn13: '73999140774',
// 	// 	num_pages: 298,
// 	// 	publication_date: '2000-04-01',
// 	// 	//language_Id: 2,
// 	// 	//publisher_Id: 10,
// 	// },
// 	// {
// 	// 	title: 'William Goldman: Four Screenplays',
// 	// 	isbn13: '73999254907',
// 	// 	num_pages: 504,
// 	// 	publication_date: '2000-05-01',
// 	// 	//language_Id: 2,
// 	// 	//publisher_Id: 30,
// 	// },
// 	// {
// 	// 	title: 'The Season: A Candid Look at Broadway',
// 	// 	isbn13: '73999768442',
// 	// 	num_pages: 448,
// 	// 	publication_date: '2004-07-01',
// 	// 	//language_Id: 1,
// 	// 	//publisher_Id: 36,
// 	// },
// 	// {
// 	// 	title: 'The Beatles Complete - Updated Edition',
// 	// 	isbn13: '73999960822',
// 	// 	num_pages: 303,
// 	// 	publication_date: '1986-12-01',
// 	// 	//language_Id: 1,
// 	// 	//publisher_Id: 5,
// 	// },
// 	// {
// 	// 	title: 'Working Effectively with Legacy Code',
// 	// 	isbn13: '76092025986',
// 	// 	num_pages: 464,
// 	// 	publication_date: '2004-09-01',
// 	// 	//language_Id: 1,
// 	// 	//publisher_Id: 21,
// 	// },
// 	// {
// 	// 	title: 'The Complete Anne of Green Gables Boxed Set (Anne of Green Gables  #1-8}',
// 	// 	isbn13: '76783609419',
// 	// 	num_pages: 138,
// 	// 	publication_date: '1998-10-0611',
// 	// 	//language_Id: 5,
// 	// 	//publisher_Id: 31,
// 	// },
// 	// {
// 	// 	title: 'Plants Bite Back! (DK Readers}',
// 	// 	isbn13: '635517047547',
// 	// 	num_pages: 148,
// 	// 	publication_date: '1999-10-25',
// 	// 	//language_Id: 1,
// 	// 	//publisher_Id: 7,
// 	// },
// 	// {
// 	// 	title: 'The Book of Awakening: Having the Life You Want by Being Present to the Life You Have',
// 	// 	isbn13: '645241001173',
// 	// 	num_pages: 438,
// 	// 	publication_date: '2000-05-31',
// 	// 	//publisher_Id: 5,
// 	// },
// 	// {
// 	// 	title: 'Risotto: 30 Simply Delicious Vegetarian Recipes from an Italian Kitchen',
// 	// 	isbn13: '694055000612',
// 	// 	num_pages: 64,
// 	// 	publication_date: '2001-03-01',
// 	// 	//language_Id: 12,
// 	// 	//publisher_Id: 1739,
// 	// },
// 	// {
// 	// 	title: 'Prétear  Vol. 3 (Prétear  #3}',
// 	// 	isbn13: '702727014581',
// 	// 	num_pages: 172,
// 	// 	publication_date: '2004-10-12',
// 	// 	//language_Id: 3,
// 	// 	//publisher_Id: 35,
// 	// },
// 	// {
// 	// 	title: 'The Mystery in the Rocky Mountains',
// 	// 	isbn13: '710430023622',
// 	// 	num_pages: 145,
// 	// 	publication_date: '2001-04-01',
// 	// 	//language_Id: 3,
// 	// 	//publisher_Id: 5,
// 	// },
// 	// {
// 	// 	title: 'The Mystery on the Mighty Mississippi',
// 	// 	isbn13: '710430023639',
// 	// 	num_pages: 142,
// 	// 	publication_date: '2001-04-01',
// 	// 	//language_Id: 3,
// 	// 	//publisher_Id: 4,
// 	// },
// 	// {
// 	// 	title: 'Programming in C',
// 	// 	isbn13: '752063326664',
// 	// 	num_pages: 576,
// 	// 	publication_date: '2004-07-08',
// 	// 	//language_Id: 3,
// 	// 	//publisher_Id: 17,
// 	// },
// 	// {
// 	// 	title: 'PHP and MySQL Web Development (Developer\'s Library}',
// 	// 	isbn13: '752063326725',
// 	// 	num_pages: 1008,
// 	// 	publication_date: '2004-10-01',
// 	// 	//language_Id: 3,
// 	// 	//publisher_Id: 17,
// 	// },
// 	// {
// 	// 	title: 'Manhunt Official Strategy Guide',
// 	// 	isbn13: '752073003227',
// 	// 	num_pages: 175,
// 	// 	publication_date: '2003-11-25',
// 	// 	//language_Id: 2,
// 	// 	//publisher_Id: 313,
// 	// },
// 	// {
// 	// 	title: 'Living La Dolce Vita: Bring the Passion  Laughter  and Serenity of Italy Into Your Daily Life',
// 	// 	isbn13: '760789719271',
// 	// 	num_pages: 272,
// 	// 	publication_date: '2003-04-01',
// 	// 	//language_Id: 3,
// 	// 	//publisher_Id: 1859,
// 	// },
// 	// {
// 	// 	title: 'Aliens: Original Sin',
// 	// 	isbn13: '761568107371',
// 	// 	num_pages: 256,
// 	// 	publication_date: '2005-10-26',
// 	// 	//language_Id: 10,
// 	// 	//publisher_Id: 30,
// 	// },
// 	// {
// 	// 	title: 'The Zen of CSS Design: Visual Enlightenment for the Web',
// 	// 	isbn13: '785342303476',
// 	// 	num_pages: 296,
// 	// 	publication_date: '2005-02-17',
// 	// 	//language_Id: 3,
// 	// 	//publisher_Id: 1461,
// 	// },
// 	// {
// 	// 	title: 'Algorithms in C  Parts 1-4: Fundamentals  Data Structures  Sorting  Searching',
// 	// 	isbn13: '785342314526',
// 	// 	num_pages: 720,
// 	// 	publication_date: '1997-09-27',
// 	// 	//language_Id: 3,
// 	// 	//publisher_Id: 4,
// 	// },
// 	// {
// 	// 	title: 'Healing Therapies for Overcoming Insomnia',
// 	// 	isbn13: '798499100096',
// 	// 	num_pages: 175,
// 	// 	publication_date: '2005-02-23',
// 	// 	//language_Id: 3,
// 	// 	//publisher_Id: 479,
// 	// },
// 	// {
// 	// 	title: 'The Prophet',
// 	// 	isbn13: '9780001000391',
// 	// 	num_pages: 127,
// 	// 	publication_date: '2010-01-01',
// 	// 	//language_Id: 3,
// 	// 	//publisher_Id: 15,
// 	// },
// 	// {
// 	// 	title: 'Sam And The Firefly (Beginner Books}',
// 	// 	isbn13: '9780001713192',
// 	// 	num_pages: 64,
// 	// 	publication_date: '1985-06-17',
// 	// 	//language_Id: 3,
// 	// 	//publisher_Id: 25,
// 	// },
// 	// {
// 	// 	title: 'After the Funeral',
// 	// 	isbn13: '9780002310192',
// 	// 	num_pages: 25,
// 	// 	publication_date: '2001-07-02',
// 	// 	//language_Id: 3,
// 	// 	//publisher_Id: 8,
// 	// },
// 	// {
// 	// 	title: 'Sleeping Murder (Miss Marple  #13}',
// 	// 	isbn13: '9780002317856',
// 	// 	num_pages: 242,
// 	// 	publication_date: '2003-08-04',
// 	// 	//language_Id: 3,
// 	// 	//publisher_Id: 569,
// 	// },
// 	// {
// 	// 	title: 'The One Tree (The Second Chronicles of Thomas Covenant  #2}',
// 	// 	isbn13: '9780006163831',
// 	// 	num_pages: 479,
// 	// 	publication_date: '1996-11-18',
// 	// 	//language_Id: 3,
// 	// 	//publisher_Id: 23,
// 	// },
// 	// {
// 	// 	title: 'The Great And Secret Show (Book of the Art #1}',
// 	// 	isbn13: '9780006176954',
// 	// 	num_pages: 698,
// 	// 	publication_date: '1990-04-26',
// 	// 	//language_Id: 3,
// 	// 	//publisher_Id: 24,
// 	// },
// 	// {
// 	// 	title: 'Rage of Angels',
// 	// 	isbn13: '9780006178736',
// 	// 	num_pages: 512,
// 	// 	publication_date: '1999-08-03',
// 	// 	//language_Id: 3,
// 	// 	//publisher_Id: 889,
// 	// },
// 	// {
// 	// 	title: 'The Four Loves',
// 	// 	isbn13: '9780006280897',
// 	// 	num_pages: 170,
// 	// 	publication_date: '2002-06-05',
// 	// 	//language_Id: 3,
// 	// 	//publisher_Id: 891,
// 	// },
// 	// {
// 	// 	title: 'Divine Conspiracy: Rediscovering Our Hidden Life in God',
// 	// 	isbn13: '9780006281146',
// 	// 	num_pages: 384,
// 	// 	publication_date: '1998-10-05',
// 	// 	//language_Id: 3,
// 	// 	//publisher_Id: 730,
// 	// },
// 	// {
// 	// 	title: 'Agatha Christie: An Autobiography',
// 	// 	isbn13: '9780006353287',
// 	// 	num_pages: 560,
// 	// 	publication_date: '2001-01-02',
// 	// 	//language_Id: 14,
// 	// 	//publisher_Id: 2,
// 	// },
// 	// {
// 	// 	title: 'Empires of the Monsoon: A History of the Indian Ocean and Its Invaders',
// 	// 	isbn13: '9780006380832',
// 	// 	num_pages: 608,
// 	// 	publication_date: '1998-01-01',
// 	// 	//publisher_Id: 9,
// 	// },
// 	// {
// 	// 	title: 'Executive Orders (Jack Ryan  #8}',
// 	// 	isbn13: '9780006479758',
// 	// 	num_pages: 1273,
// 	// 	publication_date: '1998-01-01',
// 	// 	//language_Id: 8,
// 	// 	//publisher_Id: 2,
// 	// },
// 	// {
// 	// 	title: 'Warhost of Vastmark (Wars of Light & Shadow  #3; Arc 2 - The Ships of Merior  #2}',
// 	// 	isbn13: '9780006482079',
// 	// 	num_pages: 522,
// 	// 	publication_date: '2009-07-01',
// 	// 	langugae_Id: 10,
// 	// 	//publisher_Id: 21,
// 	// },
// 	// {
// 	// 	title: 'Sacrament',
// 	// 	isbn13: '9780006482642',
// 	// 	num_pages: 594,
// 	// 	publication_date: '1997-05-01',
// 	// 	//language_Id: 8,
// 	// 	publisher: 35,
// 	// },
// 	// {
// 	// 	title: 'Witness for the Prosecution and Selected Plays',
// 	// 	isbn13: '9780006490456',
// 	// 	num_pages: 352,
// 	// 	publication_date: '1995-10-07',
// 	// 	//language_Id: 1,
// 	// 	//publisher_Id: 18,
// 	// },
// 	// {
// 	// 	title: 'The Little House',
// 	// 	isbn13: '9780006496434',
// 	// 	num_pages: 368,
// 	// 	publication_date: '1998-02-01',
// 	// 	//language_Id: 3,
// 	// 	//publisher_Id: 29,
// 	// },
// 	// {
// 	// 	title: 'Mystical Paths (Starbridge  #5}',
// 	// 	isbn13: '9780006496878',
// 	// 	num_pages: 576,
// 	// 	publication_date: '1996-07-01',
// 	// 	//language_Id: 3,
// 	// 	//publisher_Id: 19,
// 	// },
// 	// {
// 	// 	title: 'Glittering Images (Starbridge  #1}',
// 	// 	isbn13: '9780006496892',
// 	// 	num_pages: 512,
// 	// 	publication_date: '1996-07-22',
// 	// 	//language_Id: 3,
// 	// 	//publisher_Id: 23,
// 	// },
// 	// {
// 	// 	title: 'Scandalous Risks',
// 	// 	isbn13: '9780006496908',
// 	// 	num_pages: 480,
// 	// 	publication_date: '2009-07-22',
// 	// 	//language_Id: 1,
// 	// 	//publisher_Id: 864,
// 	// },
// 	// {
// 	// 	title: 'Glamorous Powers (Starbridge  #2}',
// 	// 	isbn13: '9780006496922',
// 	// 	num_pages: 512,
// 	// 	publication_date: '1996-07-22',
// 	// 	//language_Id: 3,
// 	// 	//publisher_Id: 12,
// 	// },
// 	// {
// 	// 	title: 'The Mad Ship (Liveship Traders  #2}',
// 	// 	isbn13: '9780006498865',
// 	// 	num_pages: 906,
// 	// 	publication_date: '2008-02-04',
// 	// 	//language_Id: 3,
// 	// 	//publisher_Id: 8,
// 	// },
// 	// {
// 	// 	title: 'The Reverse of the Medal (Aubrey & Maturin #11}',
// 	// 	isbn13: '9780006499268',
// 	// 	num_pages: 261,
// 	// 	publication_date: '2010-04-01',
// 	// 	//language_Id: 3,
// 	// 	//publisher_Id: 28,
// 	// },
// 	// {
// 	// 	title: 'Miss Marple Omnibus Vol. 3 (Murder at the Vicarage / Nemesis / Sleeping Murder / At Bertram\'s Hotel}',
// 	// 	isbn13: '9780006499619',
// 	// 	num_pages: 688,
// 	// 	publication_date: '1997-07-10',
// 	// 	//language_Id: 1,
// 	// 	//publisher_Id: 9,
// 	// },
// 	// {
// 	// 	title: 'Zelda\'s Cut',
// 	// 	isbn13: '9780006511779',
// 	// 	num_pages: 432,
// 	// 	publication_date: '2001-02-01',
// 	// 	//language_Id: 1,
// 	// 	//publisher_Id: 9,
// 	// },
// 	// {
// 	// 	title: 'Spares',
// 	// 	isbn13: '9780006512677',
// 	// 	num_pages: 317,
// 	// 	publication_date: '1998-11-02',
// 	// 	//language_Id: 1,
// 	// 	//publisher_Id: 2,
// 	// },
// 	// {
// 	// 	title: 'The Wise Woman',
// 	// 	isbn13: '9780006514640',
// 	// 	num_pages: 640,
// 	// 	publication_date: '2002-02-01',
// 	// 	//language_Id: 5,
// 	// 	//publisher_Id: 9,
// 	// },
// 	// {
// 	// 	title: 'Girls\' Night In',
// 	// 	isbn13: '9780006514855',
// 	// 	num_pages: 586,
// 	// 	publication_date: '2000-07-03',
// 	// 	//language_Id: 5,
// 	// 	//publisher_Id: 28,
// 	// },
// 	// {
// 	// 	title: 'She Came to Stay',
// 	// 	isbn13: '9780006540809',
// 	// 	num_pages: 416,
// 	// 	publication_date: '1995-10-09',
// 	// 	//language_Id: 5,
// 	// 	//publisher_Id: 12,
// 	// },
// 	// {
// 	// 	title: 'The Bonesetter\'s Daughter',
// 	// 	isbn13: '9780006550433',
// 	// 	num_pages: 352,
// 	// 	publication_date: '2004-10-01',
// 	// 	//language_Id: 2,
// 	// 	//publisher_Id: 3,
// 	// },
// 	// {
// 	// 	title: 'Ocean Star Express',
// 	// 	isbn13: '9780006646006',
// 	// 	num_pages: 32,
// 	// 	publication_date: '2002-07-01',
// 	// 	//language_Id: 2,
// 	// 	//publisher_Id: 2,
// 	// },
// 	// {
// 	// 	title: 'The Collection: The Outsiders / Rumble Fish / That Was Then  This Is Now',
// 	// 	isbn13: '9780006751151',
// 	// 	num_pages: 448,
// 	// 	publication_date: '1995-06-01',
// 	// 	//language_Id: 2,
// 	// 	//publisher_Id: 9,
// 	// },
// 	// {
// 	// 	title: 'A Small Pinch of Weather',
// 	// 	isbn13: '9780006754893',
// 	// 	num_pages: 239,
// 	// 	publication_date: '2000-01-01',
// 	// 	//language_Id: 2,
// 	// 	//publisher_Id: 9,
// 	// },
// 	// {
// 	// 	title: 'Image-Music-Text',
// 	// 	isbn13: '9780006861355',
// 	// 	num_pages: 220,
// 	// 	publication_date: '1993-09-13',
// 	// 	//language_Id: 2,
// 	// 	//publisher_Id: 5,
// 	// },
// 	// {
// 	// 	title: 'The Princess of the Chalet School',
// 	// 	isbn13: '9780006906018',
// 	// 	num_pages: 159,
// 	// 	publication_date: '2000-01-01',
// 	// 	//language_Id: 2,
// 	// 	//publisher_Id: 2,
// 	// },
// 	// {
// 	// 	title: 'Grand Conspiracy (Wars of Light & Shadow #5; Arc 3 - Alliance of Light  #2}',
// 	// 	isbn13: '9780007102228',
// 	// 	num_pages: 614,
// 	// 	publication_date: '2007-11-05',
// 	// 	//language_Id: 2,
// 	// 	//publisher_Id: 10,
// 	// },
// 	// {
// 	// 	title: 'The One Minute Minute Sales Person',
// 	// 	isbn13: '9780007104840',
// 	// 	num_pages: 109,
// 	// 	publication_date: '2000-06-01',
// 	// 	//language_Id: 2,
// 	// 	//publisher_Id: 9,
// 	// },
// 	// {
// 	// 	title: 'Tree and Leaf: Includes Mythopoeia and The Homecoming of Beorhtnoth',
// 	// 	isbn13: '9780007105045',
// 	// 	num_pages: 150,
// 	// 	publication_date: '2001-02-05',
// 	// 	//language_Id: 2,
// 	// 	//publisher_Id: 19,
// 	// },
// 	// {
// 	// 	title: 'Dreamland (Dreamland  #1}',
// 	// 	isbn13: '9780007109661',
// 	// 	num_pages: 375,
// 	// 	publication_date: '2001-07-02',
// 	// 	//language_Id: 3,
// 	// 	//publisher_Id: 891,
// 	// },
// 	// {
// 	// 	title: 'Partners in Crime (Tommy and Tuppence #2}',
// 	// 	isbn13: '9780007111503',
// 	// 	num_pages: 347,
// 	// 	publication_date: '2001-01-01',
// 	// 	//language_Id: 1,
// 	// 	//publisher_Id: 9,
// 	// },
// 	// {
// 	// 	title: 'The Lord of the Rings: The Return of the King - Visual Companion',
// 	// 	isbn13: '9780007116263',
// 	// 	num_pages: 72,
// 	// 	publication_date: '2003-11-06',
// 	// 	//language_Id: 1,
// 	// 	//publisher_Id: 2,
// 	// },
// 	// {
// 	// 	title: 'All Families Are Psychotic',
// 	// 	isbn13: '9780007117536',
// 	// 	num_pages: 279,
// 	// 	publication_date: '2002-07-01',
// 	// 	//language_Id: 1,
// 	// 	//publisher_Id: 3,
// 	// },
// 	// {
// 	// 	title: 'Hallowe\'en Party (Hercule Poirot  #39)',
// 	// 	isbn13: '9780007120680',
// 	// 	num_pages: 336,
// 	// 	publication_date: '2001-09-03',
// 	// 	//language_Id: 1,
// 	// 	//publisher_Id: 64,
// 	// },
// 	// {
// 	// 	title: 'Hercule Poirot\'s Christmas (Hercule Poirot  #20}',
// 	// 	isbn13: '9780007120697',
// 	// 	num_pages: 335,
// 	// 	publication_date: '2001-09-01',
// 	// 	//language_Id: 1,
// 	// 	//publisher_Id: 9,
// 	// },
// 	// {
// 	// 	title: 'Mrs. McGinty\'s Dead (Hercule Poirot  #30}',
// 	// 	isbn13: '9780007121007',
// 	// 	num_pages: 328,
// 	// 	publication_date: '2002-07-01',
// 	// 	//language_Id: 1,
// 	// 	//publisher_Id: 9,
// 	// },
// 	// {
// 	// 	title: 'Dead Man\'s Folly (Hercule Poirot  #33}',
// 	// 	isbn13: '9780007121076',
// 	// 	num_pages: 288,
// 	// 	publication_date: '2008-07-01',
// 	// 	//language_Id: 1,
// 	// 	//publisher_Id: 9,
// 	// },
// 	// {
// 	// 	title: 'The Metaphysical Club',
// 	// 	isbn13: '9780007126903',
// 	// 	num_pages: 560,
// 	// 	publication_date: '2010-02-01',
// 	// 	//language_Id: 1,
// 	// 	//publisher_Id: 9,
// 	// },
// 	// {
// 	// 	title: 'At the Mountains of Madness and Other Novels of Terror',
// 	// 	isbn13: '9780007127771',
// 	// 	num_pages: 552,
// 	// 	publication_date: '2002-06-17',
// 	// 	//language_Id: 1,
// 	// 	//publisher_Id: 14,
// 	// },
// 	// {
// 	// 	title: 'The Lord of the Rings (The Lord of the Rings  #1-3}',
// 	// 	isbn13: '9780007136582',
// 	// 	num_pages: 1200,
// 	// 	publication_date: '2002-09-16',
// 	// 	//language_Id: 1,
// 	// 	//publisher_Id: 13,
// 	// },
// 	// {
// 	// 	title: 'The Annotated Hobbit',
// 	// 	isbn13: '9780007137275',
// 	// 	num_pages: 411,
// 	// 	publication_date: '2003-04-07',
// 	// 	//language_Id: 1,
// 	// 	//publisher_Id: 882,
// 	// },
// 	// {
// 	// 	title: 'The History of Middle-Earth Index (The History of Middle-Earth  #13}',
// 	// 	isbn13: '9780007137435',
// 	// 	num_pages: 484,
// 	// 	publication_date: '2002-08-05',
// 	// 	//language_Id: 1,
// 	// 	//publisher_Id: 2,
// 	// },
// 	// {
// 	// 	title: 'The Lord of the Rings / The Hobbit',
// 	// 	isbn13: '9780007144082',
// 	// 	num_pages: 1600,
// 	// 	publication_date: '2002-10-07',
// 	// 	//language_Id: 1,
// 	// 	//publisher_Id: 27,
// 	// },
// 	// {
// 	// 	title: 'Complete Works of Oscar Wilde',
// 	// 	isbn13: '9780007144358',
// 	// 	num_pages: 1270,
// 	// 	publication_date: '2003-08-04',
// 	// 	//language_Id: 1,
// 	// 	//publisher_Id: 9,
// 	// },
// 	// {
// 	// 	title: 'Naked Empire (Sword of Truth  #8}',
// 	// 	isbn13: '9780007145591',
// 	// 	num_pages: 685,
// 	// 	publication_date: '2004-10-01',
// 	// 	//language_Id: 1,
// 	// 	//publisher_Id: 14,
// 	// },
// 	// {
// 	// 	title: 'Roverandom',
// 	// 	isbn13: '9780007149117',
// 	// 	num_pages: 116,
// 	// 	publication_date: '2002-09-02',
// 	// 	//language_Id: 1,
// 	// 	//publisher_Id: 9,
// 	// },
// 	// {
// 	// 	title: 'Tales from the Perilous Realm',
// 	// 	isbn13: '9780007149124',
// 	// 	num_pages: 178,
// 	// 	publication_date: '2002-09-02',
// 	// 	//language_Id: 1,
// 	// 	//publisher_Id: 9,
// 	// },
// 	// {
// 	// 	title: 'The Yiddish Policemen\'s Union',
// 	// 	isbn13: '9780007149827',
// 	// 	num_pages: 414,
// 	// 	publication_date: '2007-05-01',
// 	// 	//language_Id: 1,
// 	// 	//publisher_Id: 2,
// 	// },
// 	// 	{
// 	// 		title: 'The Solace Of Leaving Early',
// 	// 		isbn13: '9780007152537',
// 	// 		num_pages: 315,
// 	// 		publication_date: '2003-11-03',
// 	// 		language_Id: 1,
// 	// 		publisher_Id: 12,
// 	// 	},
// 	// ])

// 	await knex('publisher').del()
// 	await knex('publisher').insert([
// 		{ publisher_Id: 1, publisher_name: '10/18' },
// 		{ publisher_Id: 2, publisher_name: '1st Book Library' },
// 		{ publisher_Id: 3, publisher_name: '1st World Library' },
// 		{ publisher_Id: 4, publisher_name: 'A & C Black (Childrens books)' },
// 		{ publisher_Id: 5, publisher_name: 'A Harvest Book/Harcourt Inc.' },
// 		{ publisher_Id: 6, publisher_name: 'A K PETERS' },
// 		{ publisher_Id: 7, publisher_name: 'AA World Services' },
// 		{ publisher_Id: 8, publisher_name: 'Abacus' },
// 		{ publisher_Id: 9, publisher_name: 'Abacus Books' },
// 		{ publisher_Id: 10, publisher_name: 'Abacus Books (London)' },
// 		{ publisher_Id: 11, publisher_name: 'Abdo Publishing Company' },
// 		{ publisher_Id: 12, publisher_name: 'Abingdon Press' },
// 		{ publisher_Id: 13, publisher_name: 'Abradale Books/Harry N. Abrams' },
// 		{ publisher_Id: 14, publisher_name: 'Abraham Guillen Press' },
// 		{ publisher_Id: 15, publisher_name: 'Abrams' },
// 		{ publisher_Id: 16, publisher_name: 'Absolute Press' },
// 		{ publisher_Id: 17, publisher_name: 'Abstract Studio' },
// 		{ publisher_Id: 18, publisher_name: 'Academic Press' },
// 		{ publisher_Id: 19, publisher_name: 'Academica Press' },
// 		{ publisher_Id: 20, publisher_name: 'Academy Chicago Publishers' },
// 		{ publisher_Id: 21, publisher_name: 'Ace' },
// 		{ publisher_Id: 22, publisher_name: 'Ace Book' },
// 		{ publisher_Id: 23, publisher_name: 'Ace Books' },
// 		{ publisher_Id: 24, publisher_name: 'Ace Hardcover' },
// 		{ publisher_Id: 25, publisher_name: 'Ace Trade' },
// 		{ publisher_Id: 26, publisher_name: 'Ace/SFBC' },
// 		{ publisher_Id: 27, publisher_name: 'Acento Editorial' },
// 		{ publisher_Id: 28, publisher_name: 'Acropolis Books (NY)' },
// 		{ publisher_Id: 29, publisher_name: 'Actes Sud' },
// 		{ publisher_Id: 30, publisher_name: 'Adamant Media Corporation' },
// 		{ publisher_Id: 31, publisher_name: 'Adams Media' },
// 		{ publisher_Id: 32, publisher_name: 'Addison Wesley' },
// 		{
// 			publisher_Id: 33,
// 			publisher_name: 'Addison Wesley Publishing Company',
// 		},
// 		{ publisher_Id: 34, publisher_name: 'Addison-Wesley Professional' },
// 		{ publisher_Id: 35, publisher_name: 'ADV Manga' },
// 		{ publisher_Id: 36, publisher_name: 'Advantage World Press' },
// 		{ publisher_Id: 37, publisher_name: 'Adventures Unlimited Press' },
// 		{ publisher_Id: 38, publisher_name: 'Aegypan' },
// 		{ publisher_Id: 39, publisher_name: 'Aerie' },
// 		{ publisher_Id: 40, publisher_name: 'AHA! Process' },
// 		{ publisher_Id: 41, publisher_name: 'AIT Planet Lar' },
// 		{ publisher_Id: 42, publisher_name: 'Aivia Press' },
// 		{ publisher_Id: 43, publisher_name: 'AK Press' },
// 		{ publisher_Id: 44, publisher_name: 'Akashic Books/Punk Planet Books' },
// 		{ publisher_Id: 45, publisher_name: 'Aladdin' },
// 		{ publisher_Id: 46, publisher_name: 'Aladdin Paperbacks' },
// 		{ publisher_Id: 47, publisher_name: 'Alan Rodgers Books' },
// 		{ publisher_Id: 48, publisher_name: 'Albert Whitman Company' },
// 		{ publisher_Id: 49, publisher_name: 'Albin Michel' },
// 		{ publisher_Id: 50, publisher_name: 'Albury Publishing' },
// 	])
// }
